services:
  database:
    image: mariadb:latest
    container_name: QuizIT-DB #Namen anpassen
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PW}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PW}
      DB_PORT: ${MARIADB_PORT}
    ports:
      - "${DEPLOYMENT_PORT_DB}:${MARIADB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  api:
    build: .
    image: rtarnoczi/quizit-backend:develop
    container_name: QuizIT-API #Namen anpassen
    platform: linux/arm64
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - MARIADB_HOST=database
    ports:
      - "${DEPLOYMENT_PORT_API}:${API_PORT}"
    depends_on:
      - database
    restart: always

volumes:
  db_data:

