version: '3.8'

services:
  web:
    build: .
    image: quizit-backend:latest
    container_name: QuizIT-Backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
